# Generated by Django 3.0.5 on 2020-05-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_id', models.CharField(max_length=30)),
                ('trans_id', models.CharField(max_length=50, null=True)),
                ('order_data', models.TextField()),
                ('payed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('payed', 'Оплачен'), ('new', 'Новый')], max_length=30, null=True)),
                ('type', models.CharField(choices=[('deposit', 'Депозита'), ('certificate', 'Сертификатов'), ('flightTime', 'Полетное время')], max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.DecimalField(decimal_places=0, max_digits=3)),
                ('flight_type', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('flight_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('flied', 'Отлетан'), ('payed', 'Оплачен'), ('canceled', 'Отменен')], max_length=20, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Order')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=50)),
                ('cert_number', models.CharField(max_length=50, null=True)),
                ('flight_time', models.DecimalField(decimal_places=0, max_digits=3)),
                ('is_used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Order')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
