# Generated by Django 3.0.5 on 2020-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy_deposit', 'Покупка депозита'), ('buy_certificate', 'Покупка сертификатов'), ('buy_tariff', 'Покупка полетного времени по тарифу'), ('flight_certificate', 'Бронирование полетного времени по сертификатам'), ('flight_deposit', 'Бронирование полетного времени по депозиту')], max_length=30, null=True),
        ),
    ]
