# Generated by Django 3.0.5 on 2020-06-14 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20200613_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='flights',
            name='remote_record_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Идентификатор записи на полет 1С'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(max_length=50, verbose_name='Категория сертификата'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='flight_time',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Длительность полета'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_date',
            field=models.DateTimeField(null=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_time',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Длительность полета'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='flight_type',
            field=models.CharField(max_length=50, verbose_name='Вид полета'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Отлетан'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='status',
            field=models.CharField(choices=[('flied', 'Отлетан'), ('payed', 'Оплачен'), ('canceled', 'Отменен')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.TextField(verbose_name='Детали заказа в JSON'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=30, verbose_name='Идентификатор заказа клиента 1С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Заказ оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payed', 'Оплачен'), ('new', 'Новый')], max_length=30, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy_deposit', 'Покупка депозита'), ('buy_certificate', 'Покупка сертификатов'), ('buy_tariff', 'Покупка полетного времени по тарифу'), ('flight_certificate', 'Бронирование полетного времени по сертификатам'), ('flight_deposit', 'Бронирование полетного времени по депозиту')], max_length=30, null=True, verbose_name='Вид заказа'),
        ),
    ]
