# Generated by Django 3.0.8 on 2020-07-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200614_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='status',
            field=models.CharField(choices=[('flied', 'Отлетан'), ('payed', 'Оплачен'), ('canceled', 'Отменен'), ('new', 'ОжидаетОплаты')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payed', 'Оплачен'), ('new', 'Новый'), ('confirmed', 'Подтвержден')], max_length=30, null=True, verbose_name='Статус'),
        ),
    ]
