# Generated by Django 3.0.8 on 2020-08-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200716_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name': 'Полет', 'verbose_name_plural': 'Полеты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='flights',
            name='flight_data',
            field=models.TextField(null=True, verbose_name='Детали полета в JSON'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='status',
            field=models.CharField(choices=[('flied', 'Отлетан'), ('payed', 'Оплачен'), ('canceled', 'Отменен'), ('new', 'Ожидает оплаты')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
