# Generated by Django 3.0.5 on 2020-06-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0002_auto_20200422_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deposit_available',
            field=models.BooleanField(default=False),
        ),
    ]
