# Generated by Django 3.0.8 on 2020-07-16 00:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phone_login', '0004_auto_20200613_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deposit_minutes',
            field=models.IntegerField(default=0, verbose_name='Минут на депозите'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_deposit_available',
            field=models.BooleanField(default=False, verbose_name='Депозит доступен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
